/* Generated by: ~/.sqitch/templates/deploy/create-table.tmpl */

-- Deploy dvdrental:dsa-schema/tables/json_imports to pg

BEGIN;

CREATE TABLE dsa.json_imports (
    payload json,
    LIKE rental.audit_columns INCLUDING DEFAULTS INCLUDING COMMENTS
);

COMMENT ON TABLE dsa.json_imports IS 'Table to store JSON for use by ETL functions.';

COMMENT ON COLUMN dsa.json_imports.payload IS 'Data in json format to be consumed by ETL functions.';


COMMIT;