/* Generated by: ~/.sqitch/templates/deploy/create-schema.tmpl */

-- Deploy dvdrental:rental-schema/rental to pg

BEGIN;

CREATE SCHEMA rental;
COMMENT ON SCHEMA rental IS 'Home of all things rental.';

COMMIT;