/* Generated by: ~/.sqitch/templates/deploy/create-schema.tmpl */

-- Deploy appschema:appschema_create_schema to pg

BEGIN;

CREATE SCHEMA appschema;
COMMENT ON SCHEMA appschema IS 'Home of all things appschema.';

COMMIT;