/* Generated by: ~/.sqitch/templates/deploy/create-schema.tmpl */

-- Deploy dvdrental:create_appschema to pg

BEGIN;

CREATE SCHEMA appschema;
COMMENT ON SCHEMA appschema IS 'Home of all things appschema.';

COMMIT;