/* Generated by: ~/.sqitch/templates/deploy/create-schema.tmpl */

-- Deploy dvdrental:dvdrental_create_schema to pg

BEGIN;

CREATE SCHEMA dvdrental;
COMMENT ON SCHEMA dvdrental IS 'Home of all things dvdrental.';

COMMIT;