/* Generated by: ~/.sqitch/templates/verify/create-table.tmpl */

-- Verify dvdrental:dsa-schema/tables/json_imports on pg

BEGIN;

/* Test table exists in the correct schema */
SELECT
    1 / COUNT( tables.table_name )
FROM
    information_schema.tables
WHERE
    tables.table_schema = 'dsa' AND
    tables.table_name = 'json_imports';

/* Test table has a comment */
SELECT
    1 / COUNT( pg_catalog.obj_description( pg_class.oid, 'pg_class' ) )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'dsa'
    )
WHERE
    pg_class.relname = 'json_imports';

/* Test each column has a comment */

SELECT
    1 / COUNT( pg_catalog.col_description( pg_class.oid, pg_attribute.attnum ) )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'dsa'
    )
    JOIN pg_catalog.pg_attribute ON (
        pg_attribute.attrelid = pg_class.oid AND
        pg_attribute.attnum > 0 AND
        pg_attribute.attname = 'payload'
    )
WHERE
    pg_class.relname = 'json_imports';


/* Test that each constraint has a comment */


COMMIT;