-- Deploy dvdrental:tables/address to pg
-- requires: appschema
-- requires: tables/audit_columns
-- requires: tables/lkp_global_region
-- requires: tables/lkp_global_subregion
-- requires: tables/country
-- requires: tables/city

BEGIN;

CREATE TABLE dvdrental.address (
    address_fk BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    country_fk SMALLINT NOT NULL,
    city_fk BIGINT NOT NULL,
    house_number TEXT NULL,
    street_name TEXT NULL,
    suburb_name TEXT NULL,
    county_name TEXT NULL,
    postal_code TEXT NULL,
    LIKE dvdrental.audit_columns INCLUDING DEFAULTS INCLUDING COMMENTS,
    CONSTRAINT address_pk PRIMARY KEY ( city_fk, house_number, street_name, suburb_name, county_name, postal_code ),
    CONSTRAINT country_fk FOREIGN KEY ( country_fk ) REFERENCES dvdrental.country ( country_fk ) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT city_fk FOREIGN KEY ( city_fk ) REFERENCES dvdrental.city ( city_fk ) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT address_fk_uidx UNIQUE ( address_fk )
);
COMMENT ON TABLE dvdrental.address IS 'Address information, generated by using country/city information.';

COMMENT ON COLUMN dvdrental.address.address_fk IS 'Address foreign key.';
COMMENT ON COLUMN dvdrental.address.country_fk IS 'Country foreign key to dvdrental.country.country_fk.';
COMMENT ON COLUMN dvdrental.address.city_fk IS 'Address foreign key to dvdrental.city.city_fk.';
COMMENT ON COLUMN dvdrental.address.house_number IS 'House number.';
COMMENT ON COLUMN dvdrental.address.street_name IS 'Street name.';
COMMENT ON COLUMN dvdrental.address.suburb_name IS 'Suburb name.';
COMMENT ON COLUMN dvdrental.address.county_name IS 'County name.';
COMMENT ON COLUMN dvdrental.address.postal_code IS 'Postal code.';

COMMENT ON CONSTRAINT address_pk ON dvdrental.address IS 'Primary key.';
COMMENT ON CONSTRAINT country_fk ON dvdrental.address IS 'Foreign key to dvdrental.country.country_fk.';
COMMENT ON CONSTRAINT city_fk ON dvdrental.address IS 'Foreign key to dvdrental.city.city_fk.';
COMMENT ON CONSTRAINT address_fk_uidx ON dvdrental.address IS 'Unique constraint on address_fk. Used for foreign keys or mapping tables.';

COMMIT;
