/* Generated by: ~/.sqitch/templates/deploy/create-table.tmpl */

-- Deploy dvdrental:tables/city to pg
-- requires: appschema
-- requires: tables/country
-- requires: dsaschema
-- requires: tables/json_imports

BEGIN;

CREATE TABLE dvdrental.city (
    city_fk BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    country_code SMALLINT NOT NULL,
    city_name TEXT NOT NULL,
    LIKE dvdrental.audit_columns INCLUDING DEFAULTS INCLUDING COMMENTS,
    CONSTRAINT city_pk PRIMARY KEY ( country_code, city_name ),
    CONSTRAINT city_country_code_fk FOREIGN KEY ( country_code ) REFERENCES dvdrental.country ( country_code ) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT city_name_not_empty_chk CHECK ( COALESCE( city_name, '' ) <> '' )
) PARTITION BY LIST ( country_code );

COMMENT ON TABLE dvdrental.city IS 'Add dvdrental.city table.';

COMMENT ON COLUMN dvdrental.city.city_fk IS 'City foreign key lookup.';
COMMENT ON COLUMN dvdrental.city.country_code IS 'Used for foreign key from dvdrental.city.country_code to dvdrental.country.country_code.';
COMMENT ON COLUMN dvdrental.city.city_name IS 'City name.';

COMMENT ON CONSTRAINT city_pk ON dvdrental.city IS 'Primary key on city.';
COMMENT ON CONSTRAINT city_country_code_fk ON dvdrental.city IS 'Foreign key from city.country_code to country.country_code.';
COMMENT ON CONSTRAINT city_name_not_empty_chk ON dvdrental.city IS 'City name must not be NULL or empty.';

COMMIT;