/* Generated by: ~/.sqitch/templates/deploy/create-table.tmpl */

-- Deploy dvdrental:tables/city to pg
-- requires: appschema
-- requires: tables/country
-- requires: dsaschema
-- requires: tables/json_imports

BEGIN;

CREATE TABLE rental.city (
    city_fk BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    country_code SMALLINT NOT NULL,
    city_name TEXT NOT NULL,
    LIKE rental.audit_columns INCLUDING DEFAULTS INCLUDING COMMENTS,
    CONSTRAINT city_pk PRIMARY KEY ( country_code, city_name ), 
    CONSTRAINT city_country_code_fk FOREIGN KEY ( country_code ) REFERENCES rental.country ( country_code ) DEFERRABLE INITIALLY IMMEDIATE, 
    CONSTRAINT city_name_not_empty_chk CHECK ( COALESCE( city_name, '' ) <> '' )
) PARTITION BY LIST ( country_code ); 

COMMENT ON TABLE rental.city IS 'Add rental.city table.';

COMMENT ON COLUMN rental.city.city_fk IS 'City foreign key lookup.';
COMMENT ON COLUMN rental.city.country_code IS 'Used for foreign key from rental.city.country_code to rental.country.country_code.';
COMMENT ON COLUMN rental.city.city_name IS 'City name.';

COMMENT ON CONSTRAINT city_pk ON rental.city IS 'Primary key on city.';
COMMENT ON CONSTRAINT city_country_code_fk ON rental.city IS 'Foreign key from city.country_code to country.country_code.';
COMMENT ON CONSTRAINT city_name_not_empty_chk ON rental.city IS 'City name must not be NULL or empty.';

COMMIT;