/* Generated by: ~/.sqitch/templates/verify/create-role.tmpl */

-- Verify dvdrental-web-app:roles/dbadmins on pg

BEGIN;

-- Check if the role exists.
SELECT
    1 / COUNT( pg_roles.rolname )
FROM
    pg_catalog.pg_roles
WHERE
    pg_roles.rolname = 'dbadmins';

-- Ensure the role has a comment provided.
SELECT
    1 / COUNT( pg_catalog.shobj_description( pg_roles.oid, 'pg_authid' ) )
FROM
    pg_catalog.pg_roles
WHERE
    pg_roles.rolname = 'dbadmins';

COMMIT;