/* Generated by: ~/.sqitch/templates/verify/create-schema.tmpl */

-- Verify dvdrental:dsa-schema/dsa on pg

BEGIN;

SELECT pg_catalog.has_schema_privilege( 'dbo', 'dsa', 'USAGE' );

SELECT
    1 / COUNT( pg_roles.rolname )
FROM
    pg_catalog.pg_namespace
    JOIN pg_catalog.pg_roles ON (
        pg_roles.oid = pg_namespace.nspowner AND
        pg_roles.rolname = 'dbo'
    )
WHERE
    pg_namespace.nspname = 'dsa';

SELECT
    1 / COUNT( pg_catalog.obj_description( pg_namespace.oid, 'pg_namespace' ) )
FROM
    pg_catalog.pg_namespace
WHERE
    pg_namespace.nspname = 'dsa';

COMMIT;