/* Generated by: ~/.sqitch/templates/verify/create-table.tmpl */

-- Verify dvdrental:tables/city on pg

BEGIN;

/* Test table exists in the correct schema */
SELECT
    1 / COUNT( tables.table_name )
FROM
    information_schema.tables
WHERE
    tables.table_schema = 'rental' AND
    tables.table_name = 'city';

/* Test table has a comment */
SELECT
    1 / COUNT( pg_catalog.obj_description( pg_class.oid, 'pg_class' ) )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'rental'
    )
WHERE
    pg_class.relname = 'city';

/* Test each column has a comment */

SELECT
    1 / COUNT( pg_catalog.col_description( pg_class.oid, pg_attribute.attnum ) )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'rental'
    )
    JOIN pg_catalog.pg_attribute ON (
        pg_attribute.attrelid = pg_class.oid AND
        pg_attribute.attnum > 0 AND
        pg_attribute.attname = 'city_fk'
    )
WHERE
    pg_class.relname = 'city';

SELECT
    1 / COUNT( pg_catalog.col_description( pg_class.oid, pg_attribute.attnum ) )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'rental'
    )
    JOIN pg_catalog.pg_attribute ON (
        pg_attribute.attrelid = pg_class.oid AND
        pg_attribute.attnum > 0 AND
        pg_attribute.attname = 'country_code'
    )
WHERE
    pg_class.relname = 'city';

SELECT
    1 / COUNT( pg_catalog.col_description( pg_class.oid, pg_attribute.attnum ) )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'rental'
    )
    JOIN pg_catalog.pg_attribute ON (
        pg_attribute.attrelid = pg_class.oid AND
        pg_attribute.attnum > 0 AND
        pg_attribute.attname = 'city_name'
    )
WHERE
    pg_class.relname = 'city';


/* Test that each constraint has a comment */

SELECT
    pg_catalog.obj_description( pg_constraint.oid, 'pg_constraint' )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'rental'
    )
    JOIN pg_catalog.pg_constraint ON (
        pg_constraint.conrelid = pg_class.oid AND
        pg_constraint.connamespace = pg_namespace.oid AND
        pg_constraint.conname = 'city_pk'
    )
WHERE
    pg_class.relname = 'city';

SELECT
    pg_catalog.obj_description( pg_constraint.oid, 'pg_constraint' )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'rental'
    )
    JOIN pg_catalog.pg_constraint ON (
        pg_constraint.conrelid = pg_class.oid AND
        pg_constraint.connamespace = pg_namespace.oid AND
        pg_constraint.conname = 'city_country_code_fk'
    )
WHERE
    pg_class.relname = 'city';

SELECT
    pg_catalog.obj_description( pg_constraint.oid, 'pg_constraint' )
FROM
    pg_catalog.pg_class
    JOIN pg_catalog.pg_namespace ON (
        pg_namespace.oid = pg_class.relnamespace AND
        pg_namespace.nspname = 'rental'
    )
    JOIN pg_catalog.pg_constraint ON (
        pg_constraint.conrelid = pg_class.oid AND
        pg_constraint.connamespace = pg_namespace.oid AND
        pg_constraint.conname = 'city_name_not_empty_chk'
    )
WHERE
    pg_class.relname = 'city';


COMMIT;