/* Generated by: ~/.sqitch/templates/deploy/create-role.tmpl */

-- Deploy dvdrental-web-app:roles/dbadmins to pg

BEGIN;

CREATE ROLE dbadmins WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOLOGIN
    NOREPLICATION
    NOBYPASSRLS;

COMMENT ON ROLE dbadmins IS 'Default dba group from which each dba will inherit.';

COMMIT;