/* Generated by: ~/.sqitch/templates/deploy/create-role.tmpl */

-- Deploy dvdrental-web-app:roles/manager to pg

BEGIN;

CREATE ROLE manager WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOLOGIN
    NOREPLICATION
    NOBYPASSRLS;

COMMENT ON ROLE manager IS 'Default manager group from which each managing employee will inherit.';

COMMIT;