/* Generated by: ~/.sqitch/templates/deploy/create-role.tmpl */

-- Deploy dvdrental-web-app:roles/sales to pg

BEGIN;

CREATE ROLE sales WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOLOGIN
    NOREPLICATION
    NOBYPASSRLS;

COMMENT ON ROLE sales IS 'Default sales group from which each sales employee will inherit.';

COMMIT;