/* Generated by: ~/.sqitch/templates/deploy/create-role.tmpl */

-- Deploy dvdrental-web-app:roles/stock to pg

BEGIN;

CREATE ROLE stock WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOLOGIN
    NOREPLICATION
    NOBYPASSRLS;

COMMENT ON ROLE stock IS 'Default stock group from which each stock employee will inherit.';

COMMIT;